// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CommonReq.proto

#include "CommonReq.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)
class CommonReqDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<CommonReq>
      _instance;
} _CommonReq_default_instance_;
namespace protobuf_CommonReq_2eproto {
void InitDefaultsCommonReqImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::_CommonReq_default_instance_;
    new (ptr) ::CommonReq();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::CommonReq::InitAsDefaultInstance();
}

void InitDefaultsCommonReq() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsCommonReqImpl);
}

::google::protobuf::Metadata file_level_metadata[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::CommonReq, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::CommonReq, bduss_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::CommonReq, _client_type_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::CommonReq, _client_version_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::CommonReq, _client_id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::CommonReq, apid_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::CommonReq, _phone_imei_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::CommonReq, _from_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::CommonReq, cuid_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::CommonReq, _timestamp_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::CommonReq, model_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::CommonReq, tbs_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::CommonReq, net_type_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::CommonReq, subapp_type_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::CommonReq, _phone_newimei_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::CommonReq, ka_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::CommonReq, m_api_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::CommonReq, m_logid_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::CommonReq, m_cost_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::CommonReq, m_result_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::CommonReq, m_size_u_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::CommonReq, m_size_d_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::CommonReq, smallflow_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::CommonReq, sign_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::CommonReq, pversion_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::CommonReq, brand_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::CommonReq, brand_type_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::CommonReq, lego_lib_version_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::CommonReq, applist_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::CommonReq, stoken_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::CommonReq, z_id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::CommonReq, cuid_galaxy2_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::CommonReq, cuid_gid_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::CommonReq)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::_CommonReq_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "CommonReq.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\017CommonReq.proto\"\305\004\n\tCommonReq\022\r\n\005BDUSS"
      "\030\n \001(\t\022\024\n\014_client_type\030\001 \001(\005\022\027\n\017_client_"
      "version\030\002 \001(\t\022\022\n\n_client_id\030\003 \001(\t\022\014\n\004api"
      "d\030\004 \001(\t\022\023\n\013_phone_imei\030\005 \001(\t\022\r\n\005_from\030\006 "
      "\001(\t\022\014\n\004cuid\030\007 \001(\t\022\022\n\n_timestamp\030\010 \001(\003\022\r\n"
      "\005model\030\t \001(\t\022\013\n\003tbs\030\013 \001(\t\022\020\n\010net_type\030\014 "
      "\001(\005\022\023\n\013subapp_type\030\r \001(\t\022\026\n\016_phone_newim"
      "ei\030\016 \001(\t\022\n\n\002ka\030\017 \001(\t\022\r\n\005m_api\030\020 \001(\t\022\017\n\007m"
      "_logid\030\021 \001(\t\022\016\n\006m_cost\030\022 \001(\t\022\020\n\010m_result"
      "\030\023 \001(\t\022\020\n\010m_size_u\030\024 \001(\t\022\020\n\010m_size_d\030\025 \001"
      "(\t\022\021\n\tsmallflow\030\026 \001(\t\022\014\n\004sign\030\027 \001(\t\022\020\n\010p"
      "version\030\030 \001(\t\022\r\n\005brand\030\032 \001(\t\022\022\n\nbrand_ty"
      "pe\030\033 \001(\t\022\030\n\020lego_lib_version\030\034 \001(\t\022\017\n\007ap"
      "plist\030\035 \001(\t\022\016\n\006stoken\030\036 \001(\t\022\014\n\004z_id\030\037 \001("
      "\t\022\024\n\014cuid_galaxy2\030  \001(\t\022\020\n\010cuid_gid\030! \001("
      "\tb\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 609);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "CommonReq.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_CommonReq_2eproto

// ===================================================================

void CommonReq::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int CommonReq::kBDUSSFieldNumber;
const int CommonReq::kClientTypeFieldNumber;
const int CommonReq::kClientVersionFieldNumber;
const int CommonReq::kClientIdFieldNumber;
const int CommonReq::kApidFieldNumber;
const int CommonReq::kPhoneImeiFieldNumber;
const int CommonReq::kFromFieldNumber;
const int CommonReq::kCuidFieldNumber;
const int CommonReq::kTimestampFieldNumber;
const int CommonReq::kModelFieldNumber;
const int CommonReq::kTbsFieldNumber;
const int CommonReq::kNetTypeFieldNumber;
const int CommonReq::kSubappTypeFieldNumber;
const int CommonReq::kPhoneNewimeiFieldNumber;
const int CommonReq::kKaFieldNumber;
const int CommonReq::kMApiFieldNumber;
const int CommonReq::kMLogidFieldNumber;
const int CommonReq::kMCostFieldNumber;
const int CommonReq::kMResultFieldNumber;
const int CommonReq::kMSizeUFieldNumber;
const int CommonReq::kMSizeDFieldNumber;
const int CommonReq::kSmallflowFieldNumber;
const int CommonReq::kSignFieldNumber;
const int CommonReq::kPversionFieldNumber;
const int CommonReq::kBrandFieldNumber;
const int CommonReq::kBrandTypeFieldNumber;
const int CommonReq::kLegoLibVersionFieldNumber;
const int CommonReq::kApplistFieldNumber;
const int CommonReq::kStokenFieldNumber;
const int CommonReq::kZIdFieldNumber;
const int CommonReq::kCuidGalaxy2FieldNumber;
const int CommonReq::kCuidGidFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

CommonReq::CommonReq()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_CommonReq_2eproto::InitDefaultsCommonReq();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:CommonReq)
}
CommonReq::CommonReq(const CommonReq& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  _client_version_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from._client_version().size() > 0) {
    _client_version_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from._client_version_);
  }
  _client_id_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from._client_id().size() > 0) {
    _client_id_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from._client_id_);
  }
  apid_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.apid().size() > 0) {
    apid_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.apid_);
  }
  _phone_imei_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from._phone_imei().size() > 0) {
    _phone_imei_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from._phone_imei_);
  }
  _from_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from._from().size() > 0) {
    _from_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from._from_);
  }
  cuid_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.cuid().size() > 0) {
    cuid_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.cuid_);
  }
  model_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.model().size() > 0) {
    model_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.model_);
  }
  bduss_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.bduss().size() > 0) {
    bduss_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.bduss_);
  }
  tbs_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.tbs().size() > 0) {
    tbs_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.tbs_);
  }
  subapp_type_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.subapp_type().size() > 0) {
    subapp_type_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.subapp_type_);
  }
  _phone_newimei_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from._phone_newimei().size() > 0) {
    _phone_newimei_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from._phone_newimei_);
  }
  ka_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.ka().size() > 0) {
    ka_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.ka_);
  }
  m_api_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.m_api().size() > 0) {
    m_api_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.m_api_);
  }
  m_logid_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.m_logid().size() > 0) {
    m_logid_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.m_logid_);
  }
  m_cost_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.m_cost().size() > 0) {
    m_cost_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.m_cost_);
  }
  m_result_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.m_result().size() > 0) {
    m_result_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.m_result_);
  }
  m_size_u_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.m_size_u().size() > 0) {
    m_size_u_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.m_size_u_);
  }
  m_size_d_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.m_size_d().size() > 0) {
    m_size_d_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.m_size_d_);
  }
  smallflow_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.smallflow().size() > 0) {
    smallflow_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.smallflow_);
  }
  sign_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.sign().size() > 0) {
    sign_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.sign_);
  }
  pversion_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.pversion().size() > 0) {
    pversion_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.pversion_);
  }
  brand_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.brand().size() > 0) {
    brand_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.brand_);
  }
  brand_type_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.brand_type().size() > 0) {
    brand_type_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.brand_type_);
  }
  lego_lib_version_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.lego_lib_version().size() > 0) {
    lego_lib_version_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.lego_lib_version_);
  }
  applist_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.applist().size() > 0) {
    applist_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.applist_);
  }
  stoken_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.stoken().size() > 0) {
    stoken_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.stoken_);
  }
  z_id_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.z_id().size() > 0) {
    z_id_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.z_id_);
  }
  cuid_galaxy2_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.cuid_galaxy2().size() > 0) {
    cuid_galaxy2_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.cuid_galaxy2_);
  }
  cuid_gid_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.cuid_gid().size() > 0) {
    cuid_gid_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.cuid_gid_);
  }
  ::memcpy(&_client_type_, &from._client_type_,
    static_cast<size_t>(reinterpret_cast<char*>(&_timestamp_) -
    reinterpret_cast<char*>(&_client_type_)) + sizeof(_timestamp_));
  // @@protoc_insertion_point(copy_constructor:CommonReq)
}

void CommonReq::SharedCtor() {
  _client_version_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _client_id_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  apid_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _phone_imei_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _from_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  cuid_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  model_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  bduss_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  tbs_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  subapp_type_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _phone_newimei_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ka_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  m_api_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  m_logid_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  m_cost_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  m_result_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  m_size_u_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  m_size_d_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  smallflow_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  sign_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  pversion_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  brand_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  brand_type_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  lego_lib_version_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  applist_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  stoken_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  z_id_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  cuid_galaxy2_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  cuid_gid_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&_client_type_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_timestamp_) -
      reinterpret_cast<char*>(&_client_type_)) + sizeof(_timestamp_));
  _cached_size_ = 0;
}

CommonReq::~CommonReq() {
  // @@protoc_insertion_point(destructor:CommonReq)
  SharedDtor();
}

void CommonReq::SharedDtor() {
  _client_version_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _client_id_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  apid_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _phone_imei_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _from_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  cuid_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  model_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  bduss_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  tbs_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  subapp_type_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _phone_newimei_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ka_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  m_api_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  m_logid_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  m_cost_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  m_result_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  m_size_u_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  m_size_d_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  smallflow_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  sign_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  pversion_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  brand_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  brand_type_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  lego_lib_version_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  applist_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  stoken_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  z_id_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  cuid_galaxy2_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  cuid_gid_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void CommonReq::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* CommonReq::descriptor() {
  ::protobuf_CommonReq_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_CommonReq_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const CommonReq& CommonReq::default_instance() {
  ::protobuf_CommonReq_2eproto::InitDefaultsCommonReq();
  return *internal_default_instance();
}

CommonReq* CommonReq::New(::google::protobuf::Arena* arena) const {
  CommonReq* n = new CommonReq;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void CommonReq::Clear() {
// @@protoc_insertion_point(message_clear_start:CommonReq)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _client_version_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _client_id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  apid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _phone_imei_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _from_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  cuid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  model_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  bduss_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  tbs_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  subapp_type_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _phone_newimei_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ka_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  m_api_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  m_logid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  m_cost_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  m_result_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  m_size_u_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  m_size_d_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  smallflow_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  sign_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  pversion_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  brand_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  brand_type_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  lego_lib_version_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  applist_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  stoken_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  z_id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  cuid_galaxy2_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  cuid_gid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&_client_type_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_timestamp_) -
      reinterpret_cast<char*>(&_client_type_)) + sizeof(_timestamp_));
  _internal_metadata_.Clear();
}

bool CommonReq::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:CommonReq)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(16383u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 _client_type = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &_client_type_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string _client_version = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable__client_version()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->_client_version().data(), static_cast<int>(this->_client_version().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "CommonReq._client_version"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string _client_id = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable__client_id()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->_client_id().data(), static_cast<int>(this->_client_id().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "CommonReq._client_id"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string apid = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u /* 34 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_apid()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->apid().data(), static_cast<int>(this->apid().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "CommonReq.apid"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string _phone_imei = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(42u /* 42 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable__phone_imei()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->_phone_imei().data(), static_cast<int>(this->_phone_imei().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "CommonReq._phone_imei"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string _from = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(50u /* 50 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable__from()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->_from().data(), static_cast<int>(this->_from().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "CommonReq._from"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string cuid = 7;
      case 7: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(58u /* 58 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_cuid()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->cuid().data(), static_cast<int>(this->cuid().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "CommonReq.cuid"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int64 _timestamp = 8;
      case 8: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(64u /* 64 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &_timestamp_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string model = 9;
      case 9: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(74u /* 74 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_model()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->model().data(), static_cast<int>(this->model().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "CommonReq.model"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string BDUSS = 10;
      case 10: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(82u /* 82 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_bduss()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->bduss().data(), static_cast<int>(this->bduss().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "CommonReq.BDUSS"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string tbs = 11;
      case 11: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(90u /* 90 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_tbs()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->tbs().data(), static_cast<int>(this->tbs().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "CommonReq.tbs"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 net_type = 12;
      case 12: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(96u /* 96 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &net_type_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string subapp_type = 13;
      case 13: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(106u /* 106 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_subapp_type()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->subapp_type().data(), static_cast<int>(this->subapp_type().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "CommonReq.subapp_type"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string _phone_newimei = 14;
      case 14: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(114u /* 114 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable__phone_newimei()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->_phone_newimei().data(), static_cast<int>(this->_phone_newimei().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "CommonReq._phone_newimei"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string ka = 15;
      case 15: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(122u /* 122 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_ka()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->ka().data(), static_cast<int>(this->ka().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "CommonReq.ka"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string m_api = 16;
      case 16: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(130u /* 130 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_m_api()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->m_api().data(), static_cast<int>(this->m_api().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "CommonReq.m_api"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string m_logid = 17;
      case 17: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(138u /* 138 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_m_logid()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->m_logid().data(), static_cast<int>(this->m_logid().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "CommonReq.m_logid"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string m_cost = 18;
      case 18: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(146u /* 146 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_m_cost()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->m_cost().data(), static_cast<int>(this->m_cost().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "CommonReq.m_cost"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string m_result = 19;
      case 19: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(154u /* 154 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_m_result()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->m_result().data(), static_cast<int>(this->m_result().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "CommonReq.m_result"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string m_size_u = 20;
      case 20: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(162u /* 162 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_m_size_u()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->m_size_u().data(), static_cast<int>(this->m_size_u().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "CommonReq.m_size_u"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string m_size_d = 21;
      case 21: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(170u /* 170 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_m_size_d()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->m_size_d().data(), static_cast<int>(this->m_size_d().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "CommonReq.m_size_d"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string smallflow = 22;
      case 22: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(178u /* 178 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_smallflow()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->smallflow().data(), static_cast<int>(this->smallflow().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "CommonReq.smallflow"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string sign = 23;
      case 23: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(186u /* 186 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_sign()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->sign().data(), static_cast<int>(this->sign().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "CommonReq.sign"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string pversion = 24;
      case 24: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(194u /* 194 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_pversion()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->pversion().data(), static_cast<int>(this->pversion().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "CommonReq.pversion"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string brand = 26;
      case 26: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(210u /* 210 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_brand()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->brand().data(), static_cast<int>(this->brand().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "CommonReq.brand"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string brand_type = 27;
      case 27: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(218u /* 218 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_brand_type()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->brand_type().data(), static_cast<int>(this->brand_type().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "CommonReq.brand_type"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string lego_lib_version = 28;
      case 28: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(226u /* 226 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_lego_lib_version()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->lego_lib_version().data(), static_cast<int>(this->lego_lib_version().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "CommonReq.lego_lib_version"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string applist = 29;
      case 29: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(234u /* 234 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_applist()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->applist().data(), static_cast<int>(this->applist().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "CommonReq.applist"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string stoken = 30;
      case 30: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(242u /* 242 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_stoken()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->stoken().data(), static_cast<int>(this->stoken().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "CommonReq.stoken"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string z_id = 31;
      case 31: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(250u /* 250 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_z_id()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->z_id().data(), static_cast<int>(this->z_id().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "CommonReq.z_id"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string cuid_galaxy2 = 32;
      case 32: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(2u /* 258 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_cuid_galaxy2()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->cuid_galaxy2().data(), static_cast<int>(this->cuid_galaxy2().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "CommonReq.cuid_galaxy2"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string cuid_gid = 33;
      case 33: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 266 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_cuid_gid()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->cuid_gid().data(), static_cast<int>(this->cuid_gid().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "CommonReq.cuid_gid"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:CommonReq)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:CommonReq)
  return false;
#undef DO_
}

void CommonReq::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:CommonReq)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 _client_type = 1;
  if (this->_client_type() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->_client_type(), output);
  }

  // string _client_version = 2;
  if (this->_client_version().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->_client_version().data(), static_cast<int>(this->_client_version().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "CommonReq._client_version");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->_client_version(), output);
  }

  // string _client_id = 3;
  if (this->_client_id().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->_client_id().data(), static_cast<int>(this->_client_id().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "CommonReq._client_id");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->_client_id(), output);
  }

  // string apid = 4;
  if (this->apid().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->apid().data(), static_cast<int>(this->apid().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "CommonReq.apid");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      4, this->apid(), output);
  }

  // string _phone_imei = 5;
  if (this->_phone_imei().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->_phone_imei().data(), static_cast<int>(this->_phone_imei().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "CommonReq._phone_imei");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      5, this->_phone_imei(), output);
  }

  // string _from = 6;
  if (this->_from().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->_from().data(), static_cast<int>(this->_from().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "CommonReq._from");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      6, this->_from(), output);
  }

  // string cuid = 7;
  if (this->cuid().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->cuid().data(), static_cast<int>(this->cuid().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "CommonReq.cuid");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      7, this->cuid(), output);
  }

  // int64 _timestamp = 8;
  if (this->_timestamp() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(8, this->_timestamp(), output);
  }

  // string model = 9;
  if (this->model().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->model().data(), static_cast<int>(this->model().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "CommonReq.model");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      9, this->model(), output);
  }

  // string BDUSS = 10;
  if (this->bduss().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->bduss().data(), static_cast<int>(this->bduss().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "CommonReq.BDUSS");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      10, this->bduss(), output);
  }

  // string tbs = 11;
  if (this->tbs().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->tbs().data(), static_cast<int>(this->tbs().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "CommonReq.tbs");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      11, this->tbs(), output);
  }

  // int32 net_type = 12;
  if (this->net_type() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(12, this->net_type(), output);
  }

  // string subapp_type = 13;
  if (this->subapp_type().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->subapp_type().data(), static_cast<int>(this->subapp_type().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "CommonReq.subapp_type");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      13, this->subapp_type(), output);
  }

  // string _phone_newimei = 14;
  if (this->_phone_newimei().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->_phone_newimei().data(), static_cast<int>(this->_phone_newimei().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "CommonReq._phone_newimei");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      14, this->_phone_newimei(), output);
  }

  // string ka = 15;
  if (this->ka().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->ka().data(), static_cast<int>(this->ka().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "CommonReq.ka");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      15, this->ka(), output);
  }

  // string m_api = 16;
  if (this->m_api().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->m_api().data(), static_cast<int>(this->m_api().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "CommonReq.m_api");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      16, this->m_api(), output);
  }

  // string m_logid = 17;
  if (this->m_logid().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->m_logid().data(), static_cast<int>(this->m_logid().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "CommonReq.m_logid");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      17, this->m_logid(), output);
  }

  // string m_cost = 18;
  if (this->m_cost().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->m_cost().data(), static_cast<int>(this->m_cost().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "CommonReq.m_cost");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      18, this->m_cost(), output);
  }

  // string m_result = 19;
  if (this->m_result().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->m_result().data(), static_cast<int>(this->m_result().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "CommonReq.m_result");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      19, this->m_result(), output);
  }

  // string m_size_u = 20;
  if (this->m_size_u().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->m_size_u().data(), static_cast<int>(this->m_size_u().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "CommonReq.m_size_u");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      20, this->m_size_u(), output);
  }

  // string m_size_d = 21;
  if (this->m_size_d().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->m_size_d().data(), static_cast<int>(this->m_size_d().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "CommonReq.m_size_d");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      21, this->m_size_d(), output);
  }

  // string smallflow = 22;
  if (this->smallflow().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->smallflow().data(), static_cast<int>(this->smallflow().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "CommonReq.smallflow");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      22, this->smallflow(), output);
  }

  // string sign = 23;
  if (this->sign().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->sign().data(), static_cast<int>(this->sign().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "CommonReq.sign");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      23, this->sign(), output);
  }

  // string pversion = 24;
  if (this->pversion().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->pversion().data(), static_cast<int>(this->pversion().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "CommonReq.pversion");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      24, this->pversion(), output);
  }

  // string brand = 26;
  if (this->brand().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->brand().data(), static_cast<int>(this->brand().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "CommonReq.brand");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      26, this->brand(), output);
  }

  // string brand_type = 27;
  if (this->brand_type().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->brand_type().data(), static_cast<int>(this->brand_type().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "CommonReq.brand_type");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      27, this->brand_type(), output);
  }

  // string lego_lib_version = 28;
  if (this->lego_lib_version().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->lego_lib_version().data(), static_cast<int>(this->lego_lib_version().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "CommonReq.lego_lib_version");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      28, this->lego_lib_version(), output);
  }

  // string applist = 29;
  if (this->applist().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->applist().data(), static_cast<int>(this->applist().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "CommonReq.applist");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      29, this->applist(), output);
  }

  // string stoken = 30;
  if (this->stoken().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->stoken().data(), static_cast<int>(this->stoken().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "CommonReq.stoken");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      30, this->stoken(), output);
  }

  // string z_id = 31;
  if (this->z_id().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->z_id().data(), static_cast<int>(this->z_id().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "CommonReq.z_id");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      31, this->z_id(), output);
  }

  // string cuid_galaxy2 = 32;
  if (this->cuid_galaxy2().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->cuid_galaxy2().data(), static_cast<int>(this->cuid_galaxy2().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "CommonReq.cuid_galaxy2");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      32, this->cuid_galaxy2(), output);
  }

  // string cuid_gid = 33;
  if (this->cuid_gid().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->cuid_gid().data(), static_cast<int>(this->cuid_gid().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "CommonReq.cuid_gid");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      33, this->cuid_gid(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:CommonReq)
}

::google::protobuf::uint8* CommonReq::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:CommonReq)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 _client_type = 1;
  if (this->_client_type() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->_client_type(), target);
  }

  // string _client_version = 2;
  if (this->_client_version().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->_client_version().data(), static_cast<int>(this->_client_version().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "CommonReq._client_version");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->_client_version(), target);
  }

  // string _client_id = 3;
  if (this->_client_id().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->_client_id().data(), static_cast<int>(this->_client_id().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "CommonReq._client_id");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->_client_id(), target);
  }

  // string apid = 4;
  if (this->apid().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->apid().data(), static_cast<int>(this->apid().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "CommonReq.apid");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        4, this->apid(), target);
  }

  // string _phone_imei = 5;
  if (this->_phone_imei().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->_phone_imei().data(), static_cast<int>(this->_phone_imei().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "CommonReq._phone_imei");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        5, this->_phone_imei(), target);
  }

  // string _from = 6;
  if (this->_from().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->_from().data(), static_cast<int>(this->_from().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "CommonReq._from");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        6, this->_from(), target);
  }

  // string cuid = 7;
  if (this->cuid().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->cuid().data(), static_cast<int>(this->cuid().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "CommonReq.cuid");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        7, this->cuid(), target);
  }

  // int64 _timestamp = 8;
  if (this->_timestamp() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(8, this->_timestamp(), target);
  }

  // string model = 9;
  if (this->model().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->model().data(), static_cast<int>(this->model().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "CommonReq.model");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        9, this->model(), target);
  }

  // string BDUSS = 10;
  if (this->bduss().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->bduss().data(), static_cast<int>(this->bduss().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "CommonReq.BDUSS");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        10, this->bduss(), target);
  }

  // string tbs = 11;
  if (this->tbs().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->tbs().data(), static_cast<int>(this->tbs().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "CommonReq.tbs");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        11, this->tbs(), target);
  }

  // int32 net_type = 12;
  if (this->net_type() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(12, this->net_type(), target);
  }

  // string subapp_type = 13;
  if (this->subapp_type().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->subapp_type().data(), static_cast<int>(this->subapp_type().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "CommonReq.subapp_type");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        13, this->subapp_type(), target);
  }

  // string _phone_newimei = 14;
  if (this->_phone_newimei().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->_phone_newimei().data(), static_cast<int>(this->_phone_newimei().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "CommonReq._phone_newimei");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        14, this->_phone_newimei(), target);
  }

  // string ka = 15;
  if (this->ka().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->ka().data(), static_cast<int>(this->ka().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "CommonReq.ka");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        15, this->ka(), target);
  }

  // string m_api = 16;
  if (this->m_api().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->m_api().data(), static_cast<int>(this->m_api().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "CommonReq.m_api");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        16, this->m_api(), target);
  }

  // string m_logid = 17;
  if (this->m_logid().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->m_logid().data(), static_cast<int>(this->m_logid().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "CommonReq.m_logid");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        17, this->m_logid(), target);
  }

  // string m_cost = 18;
  if (this->m_cost().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->m_cost().data(), static_cast<int>(this->m_cost().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "CommonReq.m_cost");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        18, this->m_cost(), target);
  }

  // string m_result = 19;
  if (this->m_result().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->m_result().data(), static_cast<int>(this->m_result().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "CommonReq.m_result");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        19, this->m_result(), target);
  }

  // string m_size_u = 20;
  if (this->m_size_u().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->m_size_u().data(), static_cast<int>(this->m_size_u().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "CommonReq.m_size_u");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        20, this->m_size_u(), target);
  }

  // string m_size_d = 21;
  if (this->m_size_d().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->m_size_d().data(), static_cast<int>(this->m_size_d().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "CommonReq.m_size_d");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        21, this->m_size_d(), target);
  }

  // string smallflow = 22;
  if (this->smallflow().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->smallflow().data(), static_cast<int>(this->smallflow().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "CommonReq.smallflow");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        22, this->smallflow(), target);
  }

  // string sign = 23;
  if (this->sign().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->sign().data(), static_cast<int>(this->sign().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "CommonReq.sign");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        23, this->sign(), target);
  }

  // string pversion = 24;
  if (this->pversion().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->pversion().data(), static_cast<int>(this->pversion().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "CommonReq.pversion");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        24, this->pversion(), target);
  }

  // string brand = 26;
  if (this->brand().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->brand().data(), static_cast<int>(this->brand().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "CommonReq.brand");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        26, this->brand(), target);
  }

  // string brand_type = 27;
  if (this->brand_type().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->brand_type().data(), static_cast<int>(this->brand_type().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "CommonReq.brand_type");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        27, this->brand_type(), target);
  }

  // string lego_lib_version = 28;
  if (this->lego_lib_version().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->lego_lib_version().data(), static_cast<int>(this->lego_lib_version().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "CommonReq.lego_lib_version");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        28, this->lego_lib_version(), target);
  }

  // string applist = 29;
  if (this->applist().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->applist().data(), static_cast<int>(this->applist().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "CommonReq.applist");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        29, this->applist(), target);
  }

  // string stoken = 30;
  if (this->stoken().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->stoken().data(), static_cast<int>(this->stoken().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "CommonReq.stoken");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        30, this->stoken(), target);
  }

  // string z_id = 31;
  if (this->z_id().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->z_id().data(), static_cast<int>(this->z_id().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "CommonReq.z_id");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        31, this->z_id(), target);
  }

  // string cuid_galaxy2 = 32;
  if (this->cuid_galaxy2().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->cuid_galaxy2().data(), static_cast<int>(this->cuid_galaxy2().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "CommonReq.cuid_galaxy2");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        32, this->cuid_galaxy2(), target);
  }

  // string cuid_gid = 33;
  if (this->cuid_gid().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->cuid_gid().data(), static_cast<int>(this->cuid_gid().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "CommonReq.cuid_gid");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        33, this->cuid_gid(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CommonReq)
  return target;
}

size_t CommonReq::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:CommonReq)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string _client_version = 2;
  if (this->_client_version().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->_client_version());
  }

  // string _client_id = 3;
  if (this->_client_id().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->_client_id());
  }

  // string apid = 4;
  if (this->apid().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->apid());
  }

  // string _phone_imei = 5;
  if (this->_phone_imei().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->_phone_imei());
  }

  // string _from = 6;
  if (this->_from().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->_from());
  }

  // string cuid = 7;
  if (this->cuid().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->cuid());
  }

  // string model = 9;
  if (this->model().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->model());
  }

  // string BDUSS = 10;
  if (this->bduss().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->bduss());
  }

  // string tbs = 11;
  if (this->tbs().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->tbs());
  }

  // string subapp_type = 13;
  if (this->subapp_type().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->subapp_type());
  }

  // string _phone_newimei = 14;
  if (this->_phone_newimei().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->_phone_newimei());
  }

  // string ka = 15;
  if (this->ka().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->ka());
  }

  // string m_api = 16;
  if (this->m_api().size() > 0) {
    total_size += 2 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->m_api());
  }

  // string m_logid = 17;
  if (this->m_logid().size() > 0) {
    total_size += 2 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->m_logid());
  }

  // string m_cost = 18;
  if (this->m_cost().size() > 0) {
    total_size += 2 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->m_cost());
  }

  // string m_result = 19;
  if (this->m_result().size() > 0) {
    total_size += 2 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->m_result());
  }

  // string m_size_u = 20;
  if (this->m_size_u().size() > 0) {
    total_size += 2 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->m_size_u());
  }

  // string m_size_d = 21;
  if (this->m_size_d().size() > 0) {
    total_size += 2 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->m_size_d());
  }

  // string smallflow = 22;
  if (this->smallflow().size() > 0) {
    total_size += 2 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->smallflow());
  }

  // string sign = 23;
  if (this->sign().size() > 0) {
    total_size += 2 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->sign());
  }

  // string pversion = 24;
  if (this->pversion().size() > 0) {
    total_size += 2 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->pversion());
  }

  // string brand = 26;
  if (this->brand().size() > 0) {
    total_size += 2 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->brand());
  }

  // string brand_type = 27;
  if (this->brand_type().size() > 0) {
    total_size += 2 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->brand_type());
  }

  // string lego_lib_version = 28;
  if (this->lego_lib_version().size() > 0) {
    total_size += 2 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->lego_lib_version());
  }

  // string applist = 29;
  if (this->applist().size() > 0) {
    total_size += 2 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->applist());
  }

  // string stoken = 30;
  if (this->stoken().size() > 0) {
    total_size += 2 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->stoken());
  }

  // string z_id = 31;
  if (this->z_id().size() > 0) {
    total_size += 2 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->z_id());
  }

  // string cuid_galaxy2 = 32;
  if (this->cuid_galaxy2().size() > 0) {
    total_size += 2 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->cuid_galaxy2());
  }

  // string cuid_gid = 33;
  if (this->cuid_gid().size() > 0) {
    total_size += 2 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->cuid_gid());
  }

  // int32 _client_type = 1;
  if (this->_client_type() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->_client_type());
  }

  // int32 net_type = 12;
  if (this->net_type() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->net_type());
  }

  // int64 _timestamp = 8;
  if (this->_timestamp() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->_timestamp());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CommonReq::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:CommonReq)
  GOOGLE_DCHECK_NE(&from, this);
  const CommonReq* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const CommonReq>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:CommonReq)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:CommonReq)
    MergeFrom(*source);
  }
}

void CommonReq::MergeFrom(const CommonReq& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:CommonReq)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._client_version().size() > 0) {

    _client_version_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from._client_version_);
  }
  if (from._client_id().size() > 0) {

    _client_id_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from._client_id_);
  }
  if (from.apid().size() > 0) {

    apid_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.apid_);
  }
  if (from._phone_imei().size() > 0) {

    _phone_imei_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from._phone_imei_);
  }
  if (from._from().size() > 0) {

    _from_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from._from_);
  }
  if (from.cuid().size() > 0) {

    cuid_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.cuid_);
  }
  if (from.model().size() > 0) {

    model_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.model_);
  }
  if (from.bduss().size() > 0) {

    bduss_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.bduss_);
  }
  if (from.tbs().size() > 0) {

    tbs_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.tbs_);
  }
  if (from.subapp_type().size() > 0) {

    subapp_type_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.subapp_type_);
  }
  if (from._phone_newimei().size() > 0) {

    _phone_newimei_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from._phone_newimei_);
  }
  if (from.ka().size() > 0) {

    ka_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.ka_);
  }
  if (from.m_api().size() > 0) {

    m_api_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.m_api_);
  }
  if (from.m_logid().size() > 0) {

    m_logid_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.m_logid_);
  }
  if (from.m_cost().size() > 0) {

    m_cost_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.m_cost_);
  }
  if (from.m_result().size() > 0) {

    m_result_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.m_result_);
  }
  if (from.m_size_u().size() > 0) {

    m_size_u_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.m_size_u_);
  }
  if (from.m_size_d().size() > 0) {

    m_size_d_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.m_size_d_);
  }
  if (from.smallflow().size() > 0) {

    smallflow_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.smallflow_);
  }
  if (from.sign().size() > 0) {

    sign_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.sign_);
  }
  if (from.pversion().size() > 0) {

    pversion_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.pversion_);
  }
  if (from.brand().size() > 0) {

    brand_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.brand_);
  }
  if (from.brand_type().size() > 0) {

    brand_type_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.brand_type_);
  }
  if (from.lego_lib_version().size() > 0) {

    lego_lib_version_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.lego_lib_version_);
  }
  if (from.applist().size() > 0) {

    applist_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.applist_);
  }
  if (from.stoken().size() > 0) {

    stoken_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.stoken_);
  }
  if (from.z_id().size() > 0) {

    z_id_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.z_id_);
  }
  if (from.cuid_galaxy2().size() > 0) {

    cuid_galaxy2_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.cuid_galaxy2_);
  }
  if (from.cuid_gid().size() > 0) {

    cuid_gid_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.cuid_gid_);
  }
  if (from._client_type() != 0) {
    set__client_type(from._client_type());
  }
  if (from.net_type() != 0) {
    set_net_type(from.net_type());
  }
  if (from._timestamp() != 0) {
    set__timestamp(from._timestamp());
  }
}

void CommonReq::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:CommonReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CommonReq::CopyFrom(const CommonReq& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:CommonReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CommonReq::IsInitialized() const {
  return true;
}

void CommonReq::Swap(CommonReq* other) {
  if (other == this) return;
  InternalSwap(other);
}
void CommonReq::InternalSwap(CommonReq* other) {
  using std::swap;
  _client_version_.Swap(&other->_client_version_);
  _client_id_.Swap(&other->_client_id_);
  apid_.Swap(&other->apid_);
  _phone_imei_.Swap(&other->_phone_imei_);
  _from_.Swap(&other->_from_);
  cuid_.Swap(&other->cuid_);
  model_.Swap(&other->model_);
  bduss_.Swap(&other->bduss_);
  tbs_.Swap(&other->tbs_);
  subapp_type_.Swap(&other->subapp_type_);
  _phone_newimei_.Swap(&other->_phone_newimei_);
  ka_.Swap(&other->ka_);
  m_api_.Swap(&other->m_api_);
  m_logid_.Swap(&other->m_logid_);
  m_cost_.Swap(&other->m_cost_);
  m_result_.Swap(&other->m_result_);
  m_size_u_.Swap(&other->m_size_u_);
  m_size_d_.Swap(&other->m_size_d_);
  smallflow_.Swap(&other->smallflow_);
  sign_.Swap(&other->sign_);
  pversion_.Swap(&other->pversion_);
  brand_.Swap(&other->brand_);
  brand_type_.Swap(&other->brand_type_);
  lego_lib_version_.Swap(&other->lego_lib_version_);
  applist_.Swap(&other->applist_);
  stoken_.Swap(&other->stoken_);
  z_id_.Swap(&other->z_id_);
  cuid_galaxy2_.Swap(&other->cuid_galaxy2_);
  cuid_gid_.Swap(&other->cuid_gid_);
  swap(_client_type_, other->_client_type_);
  swap(net_type_, other->net_type_);
  swap(_timestamp_, other->_timestamp_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata CommonReq::GetMetadata() const {
  protobuf_CommonReq_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_CommonReq_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
