// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FrsPageReqIdl.proto
#define PROTOBUF_USE_DLLS
#ifndef PROTOBUF_FrsPageReqIdl_2eproto__INCLUDED
#define PROTOBUF_FrsPageReqIdl_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "CommonReq.pb.h"
// @@protoc_insertion_point(includes)

namespace protobuf_FrsPageReqIdl_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[2];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsFrsPageReqIdl_DataReqImpl();
void InitDefaultsFrsPageReqIdl_DataReq();
void InitDefaultsFrsPageReqIdlImpl();
void InitDefaultsFrsPageReqIdl();
inline void InitDefaults() {
  InitDefaultsFrsPageReqIdl_DataReq();
  InitDefaultsFrsPageReqIdl();
}
}  // namespace protobuf_FrsPageReqIdl_2eproto
class FrsPageReqIdl;
class FrsPageReqIdlDefaultTypeInternal;
extern FrsPageReqIdlDefaultTypeInternal _FrsPageReqIdl_default_instance_;
class FrsPageReqIdl_DataReq;
class FrsPageReqIdl_DataReqDefaultTypeInternal;
extern FrsPageReqIdl_DataReqDefaultTypeInternal _FrsPageReqIdl_DataReq_default_instance_;

// ===================================================================

class FrsPageReqIdl_DataReq : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:FrsPageReqIdl.DataReq) */ {
 public:
  FrsPageReqIdl_DataReq();
  virtual ~FrsPageReqIdl_DataReq();

  FrsPageReqIdl_DataReq(const FrsPageReqIdl_DataReq& from);

  inline FrsPageReqIdl_DataReq& operator=(const FrsPageReqIdl_DataReq& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  FrsPageReqIdl_DataReq(FrsPageReqIdl_DataReq&& from) noexcept
    : FrsPageReqIdl_DataReq() {
    *this = ::std::move(from);
  }

  inline FrsPageReqIdl_DataReq& operator=(FrsPageReqIdl_DataReq&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const FrsPageReqIdl_DataReq& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const FrsPageReqIdl_DataReq* internal_default_instance() {
    return reinterpret_cast<const FrsPageReqIdl_DataReq*>(
               &_FrsPageReqIdl_DataReq_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(FrsPageReqIdl_DataReq* other);
  friend void swap(FrsPageReqIdl_DataReq& a, FrsPageReqIdl_DataReq& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline FrsPageReqIdl_DataReq* New() const PROTOBUF_FINAL { return New(NULL); }

  FrsPageReqIdl_DataReq* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const FrsPageReqIdl_DataReq& from);
  void MergeFrom(const FrsPageReqIdl_DataReq& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(FrsPageReqIdl_DataReq* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string kw = 1;
  void clear_kw();
  static const int kKwFieldNumber = 1;
  const ::std::string& kw() const;
  void set_kw(const ::std::string& value);
  #if LANG_CXX11
  void set_kw(::std::string&& value);
  #endif
  void set_kw(const char* value);
  void set_kw(const char* value, size_t size);
  ::std::string* mutable_kw();
  ::std::string* release_kw();
  void set_allocated_kw(::std::string* kw);

  // .CommonReq common = 39;
  bool has_common() const;
  void clear_common();
  static const int kCommonFieldNumber = 39;
  const ::CommonReq& common() const;
  ::CommonReq* release_common();
  ::CommonReq* mutable_common();
  void set_allocated_common(::CommonReq* common);

  // int32 rn = 2;
  void clear_rn();
  static const int kRnFieldNumber = 2;
  ::google::protobuf::int32 rn() const;
  void set_rn(::google::protobuf::int32 value);

  // int32 rn_need = 3;
  void clear_rn_need();
  static const int kRnNeedFieldNumber = 3;
  ::google::protobuf::int32 rn_need() const;
  void set_rn_need(::google::protobuf::int32 value);

  // int32 is_good = 4;
  void clear_is_good();
  static const int kIsGoodFieldNumber = 4;
  ::google::protobuf::int32 is_good() const;
  void set_is_good(::google::protobuf::int32 value);

  // int32 cid = 5;
  void clear_cid();
  static const int kCidFieldNumber = 5;
  ::google::protobuf::int32 cid() const;
  void set_cid(::google::protobuf::int32 value);

  // int32 with_group = 8;
  void clear_with_group();
  static const int kWithGroupFieldNumber = 8;
  ::google::protobuf::int32 with_group() const;
  void set_with_group(::google::protobuf::int32 value);

  // int32 q_type = 14;
  void clear_q_type();
  static const int kQTypeFieldNumber = 14;
  ::google::protobuf::int32 q_type() const;
  void set_q_type(::google::protobuf::int32 value);

  // int32 pn = 15;
  void clear_pn();
  static const int kPnFieldNumber = 15;
  ::google::protobuf::int32 pn() const;
  void set_pn(::google::protobuf::int32 value);

  // int32 sort_type = 47;
  void clear_sort_type();
  static const int kSortTypeFieldNumber = 47;
  ::google::protobuf::int32 sort_type() const;
  void set_sort_type(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:FrsPageReqIdl.DataReq)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr kw_;
  ::CommonReq* common_;
  ::google::protobuf::int32 rn_;
  ::google::protobuf::int32 rn_need_;
  ::google::protobuf::int32 is_good_;
  ::google::protobuf::int32 cid_;
  ::google::protobuf::int32 with_group_;
  ::google::protobuf::int32 q_type_;
  ::google::protobuf::int32 pn_;
  ::google::protobuf::int32 sort_type_;
  mutable int _cached_size_;
  friend struct ::protobuf_FrsPageReqIdl_2eproto::TableStruct;
  friend void ::protobuf_FrsPageReqIdl_2eproto::InitDefaultsFrsPageReqIdl_DataReqImpl();
};
// -------------------------------------------------------------------

class FrsPageReqIdl : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:FrsPageReqIdl) */ {
 public:
  FrsPageReqIdl();
  virtual ~FrsPageReqIdl();

  FrsPageReqIdl(const FrsPageReqIdl& from);

  inline FrsPageReqIdl& operator=(const FrsPageReqIdl& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  FrsPageReqIdl(FrsPageReqIdl&& from) noexcept
    : FrsPageReqIdl() {
    *this = ::std::move(from);
  }

  inline FrsPageReqIdl& operator=(FrsPageReqIdl&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const FrsPageReqIdl& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const FrsPageReqIdl* internal_default_instance() {
    return reinterpret_cast<const FrsPageReqIdl*>(
               &_FrsPageReqIdl_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(FrsPageReqIdl* other);
  friend void swap(FrsPageReqIdl& a, FrsPageReqIdl& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline FrsPageReqIdl* New() const PROTOBUF_FINAL { return New(NULL); }

  FrsPageReqIdl* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const FrsPageReqIdl& from);
  void MergeFrom(const FrsPageReqIdl& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(FrsPageReqIdl* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  typedef FrsPageReqIdl_DataReq DataReq;

  // accessors -------------------------------------------------------

  // .FrsPageReqIdl.DataReq data = 1;
  bool has_data() const;
  void clear_data();
  static const int kDataFieldNumber = 1;
  const ::FrsPageReqIdl_DataReq& data() const;
  ::FrsPageReqIdl_DataReq* release_data();
  ::FrsPageReqIdl_DataReq* mutable_data();
  void set_allocated_data(::FrsPageReqIdl_DataReq* data);

  // @@protoc_insertion_point(class_scope:FrsPageReqIdl)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::FrsPageReqIdl_DataReq* data_;
  mutable int _cached_size_;
  friend struct ::protobuf_FrsPageReqIdl_2eproto::TableStruct;
  friend void ::protobuf_FrsPageReqIdl_2eproto::InitDefaultsFrsPageReqIdlImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// FrsPageReqIdl_DataReq

// .CommonReq common = 39;
inline bool FrsPageReqIdl_DataReq::has_common() const {
  return this != internal_default_instance() && common_ != NULL;
}
inline const ::CommonReq& FrsPageReqIdl_DataReq::common() const {
  const ::CommonReq* p = common_;
  // @@protoc_insertion_point(field_get:FrsPageReqIdl.DataReq.common)
  return p != NULL ? *p : *reinterpret_cast<const ::CommonReq*>(
      &::_CommonReq_default_instance_);
}
inline ::CommonReq* FrsPageReqIdl_DataReq::release_common() {
  // @@protoc_insertion_point(field_release:FrsPageReqIdl.DataReq.common)
  
  ::CommonReq* temp = common_;
  common_ = NULL;
  return temp;
}
inline ::CommonReq* FrsPageReqIdl_DataReq::mutable_common() {
  
  if (common_ == NULL) {
    common_ = new ::CommonReq;
  }
  // @@protoc_insertion_point(field_mutable:FrsPageReqIdl.DataReq.common)
  return common_;
}
inline void FrsPageReqIdl_DataReq::set_allocated_common(::CommonReq* common) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(common_);
  }
  if (common) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      common = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, common, submessage_arena);
    }
    
  } else {
    
  }
  common_ = common;
  // @@protoc_insertion_point(field_set_allocated:FrsPageReqIdl.DataReq.common)
}

// string kw = 1;
inline void FrsPageReqIdl_DataReq::clear_kw() {
  kw_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& FrsPageReqIdl_DataReq::kw() const {
  // @@protoc_insertion_point(field_get:FrsPageReqIdl.DataReq.kw)
  return kw_.GetNoArena();
}
inline void FrsPageReqIdl_DataReq::set_kw(const ::std::string& value) {
  
  kw_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:FrsPageReqIdl.DataReq.kw)
}
#if LANG_CXX11
inline void FrsPageReqIdl_DataReq::set_kw(::std::string&& value) {
  
  kw_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:FrsPageReqIdl.DataReq.kw)
}
#endif
inline void FrsPageReqIdl_DataReq::set_kw(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  kw_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:FrsPageReqIdl.DataReq.kw)
}
inline void FrsPageReqIdl_DataReq::set_kw(const char* value, size_t size) {
  
  kw_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:FrsPageReqIdl.DataReq.kw)
}
inline ::std::string* FrsPageReqIdl_DataReq::mutable_kw() {
  
  // @@protoc_insertion_point(field_mutable:FrsPageReqIdl.DataReq.kw)
  return kw_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* FrsPageReqIdl_DataReq::release_kw() {
  // @@protoc_insertion_point(field_release:FrsPageReqIdl.DataReq.kw)
  
  return kw_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void FrsPageReqIdl_DataReq::set_allocated_kw(::std::string* kw) {
  if (kw != NULL) {
    
  } else {
    
  }
  kw_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), kw);
  // @@protoc_insertion_point(field_set_allocated:FrsPageReqIdl.DataReq.kw)
}

// int32 pn = 15;
inline void FrsPageReqIdl_DataReq::clear_pn() {
  pn_ = 0;
}
inline ::google::protobuf::int32 FrsPageReqIdl_DataReq::pn() const {
  // @@protoc_insertion_point(field_get:FrsPageReqIdl.DataReq.pn)
  return pn_;
}
inline void FrsPageReqIdl_DataReq::set_pn(::google::protobuf::int32 value) {
  
  pn_ = value;
  // @@protoc_insertion_point(field_set:FrsPageReqIdl.DataReq.pn)
}

// int32 rn = 2;
inline void FrsPageReqIdl_DataReq::clear_rn() {
  rn_ = 0;
}
inline ::google::protobuf::int32 FrsPageReqIdl_DataReq::rn() const {
  // @@protoc_insertion_point(field_get:FrsPageReqIdl.DataReq.rn)
  return rn_;
}
inline void FrsPageReqIdl_DataReq::set_rn(::google::protobuf::int32 value) {
  
  rn_ = value;
  // @@protoc_insertion_point(field_set:FrsPageReqIdl.DataReq.rn)
}

// int32 rn_need = 3;
inline void FrsPageReqIdl_DataReq::clear_rn_need() {
  rn_need_ = 0;
}
inline ::google::protobuf::int32 FrsPageReqIdl_DataReq::rn_need() const {
  // @@protoc_insertion_point(field_get:FrsPageReqIdl.DataReq.rn_need)
  return rn_need_;
}
inline void FrsPageReqIdl_DataReq::set_rn_need(::google::protobuf::int32 value) {
  
  rn_need_ = value;
  // @@protoc_insertion_point(field_set:FrsPageReqIdl.DataReq.rn_need)
}

// int32 cid = 5;
inline void FrsPageReqIdl_DataReq::clear_cid() {
  cid_ = 0;
}
inline ::google::protobuf::int32 FrsPageReqIdl_DataReq::cid() const {
  // @@protoc_insertion_point(field_get:FrsPageReqIdl.DataReq.cid)
  return cid_;
}
inline void FrsPageReqIdl_DataReq::set_cid(::google::protobuf::int32 value) {
  
  cid_ = value;
  // @@protoc_insertion_point(field_set:FrsPageReqIdl.DataReq.cid)
}

// int32 is_good = 4;
inline void FrsPageReqIdl_DataReq::clear_is_good() {
  is_good_ = 0;
}
inline ::google::protobuf::int32 FrsPageReqIdl_DataReq::is_good() const {
  // @@protoc_insertion_point(field_get:FrsPageReqIdl.DataReq.is_good)
  return is_good_;
}
inline void FrsPageReqIdl_DataReq::set_is_good(::google::protobuf::int32 value) {
  
  is_good_ = value;
  // @@protoc_insertion_point(field_set:FrsPageReqIdl.DataReq.is_good)
}

// int32 q_type = 14;
inline void FrsPageReqIdl_DataReq::clear_q_type() {
  q_type_ = 0;
}
inline ::google::protobuf::int32 FrsPageReqIdl_DataReq::q_type() const {
  // @@protoc_insertion_point(field_get:FrsPageReqIdl.DataReq.q_type)
  return q_type_;
}
inline void FrsPageReqIdl_DataReq::set_q_type(::google::protobuf::int32 value) {
  
  q_type_ = value;
  // @@protoc_insertion_point(field_set:FrsPageReqIdl.DataReq.q_type)
}

// int32 sort_type = 47;
inline void FrsPageReqIdl_DataReq::clear_sort_type() {
  sort_type_ = 0;
}
inline ::google::protobuf::int32 FrsPageReqIdl_DataReq::sort_type() const {
  // @@protoc_insertion_point(field_get:FrsPageReqIdl.DataReq.sort_type)
  return sort_type_;
}
inline void FrsPageReqIdl_DataReq::set_sort_type(::google::protobuf::int32 value) {
  
  sort_type_ = value;
  // @@protoc_insertion_point(field_set:FrsPageReqIdl.DataReq.sort_type)
}

// int32 with_group = 8;
inline void FrsPageReqIdl_DataReq::clear_with_group() {
  with_group_ = 0;
}
inline ::google::protobuf::int32 FrsPageReqIdl_DataReq::with_group() const {
  // @@protoc_insertion_point(field_get:FrsPageReqIdl.DataReq.with_group)
  return with_group_;
}
inline void FrsPageReqIdl_DataReq::set_with_group(::google::protobuf::int32 value) {
  
  with_group_ = value;
  // @@protoc_insertion_point(field_set:FrsPageReqIdl.DataReq.with_group)
}

// -------------------------------------------------------------------

// FrsPageReqIdl

// .FrsPageReqIdl.DataReq data = 1;
inline bool FrsPageReqIdl::has_data() const {
  return this != internal_default_instance() && data_ != NULL;
}
inline void FrsPageReqIdl::clear_data() {
  if (GetArenaNoVirtual() == NULL && data_ != NULL) {
    delete data_;
  }
  data_ = NULL;
}
inline const ::FrsPageReqIdl_DataReq& FrsPageReqIdl::data() const {
  const ::FrsPageReqIdl_DataReq* p = data_;
  // @@protoc_insertion_point(field_get:FrsPageReqIdl.data)
  return p != NULL ? *p : *reinterpret_cast<const ::FrsPageReqIdl_DataReq*>(
      &::_FrsPageReqIdl_DataReq_default_instance_);
}
inline ::FrsPageReqIdl_DataReq* FrsPageReqIdl::release_data() {
  // @@protoc_insertion_point(field_release:FrsPageReqIdl.data)
  
  ::FrsPageReqIdl_DataReq* temp = data_;
  data_ = NULL;
  return temp;
}
inline ::FrsPageReqIdl_DataReq* FrsPageReqIdl::mutable_data() {
  
  if (data_ == NULL) {
    data_ = new ::FrsPageReqIdl_DataReq;
  }
  // @@protoc_insertion_point(field_mutable:FrsPageReqIdl.data)
  return data_;
}
inline void FrsPageReqIdl::set_allocated_data(::FrsPageReqIdl_DataReq* data) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete data_;
  }
  if (data) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      data = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, data, submessage_arena);
    }
    
  } else {
    
  }
  data_ = data;
  // @@protoc_insertion_point(field_set_allocated:FrsPageReqIdl.data)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_FrsPageReqIdl_2eproto__INCLUDED
