// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PbPageReqIdl.proto

#include "PbPageReqIdl.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)
class PbPageReqIdl_DataReqDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<PbPageReqIdl_DataReq>
      _instance;
} _PbPageReqIdl_DataReq_default_instance_;
class PbPageReqIdlDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<PbPageReqIdl>
      _instance;
} _PbPageReqIdl_default_instance_;
namespace protobuf_PbPageReqIdl_2eproto {
void InitDefaultsPbPageReqIdl_DataReqImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  protobuf_CommonReq_2eproto::InitDefaultsCommonReq();
  {
    void* ptr = &::_PbPageReqIdl_DataReq_default_instance_;
    new (ptr) ::PbPageReqIdl_DataReq();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::PbPageReqIdl_DataReq::InitAsDefaultInstance();
}

void InitDefaultsPbPageReqIdl_DataReq() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsPbPageReqIdl_DataReqImpl);
}

void InitDefaultsPbPageReqIdlImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  protobuf_PbPageReqIdl_2eproto::InitDefaultsPbPageReqIdl_DataReq();
  {
    void* ptr = &::_PbPageReqIdl_default_instance_;
    new (ptr) ::PbPageReqIdl();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::PbPageReqIdl::InitAsDefaultInstance();
}

void InitDefaultsPbPageReqIdl() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsPbPageReqIdlImpl);
}

::google::protobuf::Metadata file_level_metadata[2];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::PbPageReqIdl_DataReq, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::PbPageReqIdl_DataReq, common_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::PbPageReqIdl_DataReq, kz_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::PbPageReqIdl_DataReq, r_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::PbPageReqIdl_DataReq, with_floor_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::PbPageReqIdl_DataReq, floor_rn_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::PbPageReqIdl_DataReq, rn_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::PbPageReqIdl_DataReq, q_type_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::PbPageReqIdl_DataReq, pn_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::PbPageReqIdl_DataReq, is_comm_reverse_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::PbPageReqIdl_DataReq, is_jumpfloor_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::PbPageReqIdl_DataReq, jumpfloor_num_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::PbPageReqIdl_DataReq, floor_sort_type_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::PbPageReqIdl, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::PbPageReqIdl, data_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::PbPageReqIdl_DataReq)},
  { 17, -1, sizeof(::PbPageReqIdl)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::_PbPageReqIdl_DataReq_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::_PbPageReqIdl_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "PbPageReqIdl.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 2);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\022PbPageReqIdl.proto\032\017CommonReq.proto\"\237\002"
      "\n\014PbPageReqIdl\022#\n\004data\030\001 \001(\0132\025.PbPageReq"
      "Idl.DataReq\032\351\001\n\007DataReq\022\032\n\006common\030\031 \001(\0132"
      "\n.CommonReq\022\n\n\002kz\030\004 \001(\003\022\t\n\001r\030\006 \001(\005\022\022\n\nwi"
      "th_floor\030\010 \001(\005\022\020\n\010floor_rn\030\t \001(\005\022\n\n\002rn\030\r"
      " \001(\005\022\016\n\006q_type\030\021 \001(\005\022\n\n\002pn\030\022 \001(\005\022\027\n\017is_c"
      "omm_reverse\030! \001(\005\022\024\n\014is_jumpfloor\030\" \001(\005\022"
      "\025\n\rjumpfloor_num\030# \001(\005\022\027\n\017floor_sort_typ"
      "e\030J \001(\005b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 335);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "PbPageReqIdl.proto", &protobuf_RegisterTypes);
  ::protobuf_CommonReq_2eproto::AddDescriptors();
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_PbPageReqIdl_2eproto

// ===================================================================

void PbPageReqIdl_DataReq::InitAsDefaultInstance() {
  ::_PbPageReqIdl_DataReq_default_instance_._instance.get_mutable()->common_ = const_cast< ::CommonReq*>(
      ::CommonReq::internal_default_instance());
}
void PbPageReqIdl_DataReq::clear_common() {
  if (GetArenaNoVirtual() == NULL && common_ != NULL) {
    delete common_;
  }
  common_ = NULL;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int PbPageReqIdl_DataReq::kCommonFieldNumber;
const int PbPageReqIdl_DataReq::kKzFieldNumber;
const int PbPageReqIdl_DataReq::kRFieldNumber;
const int PbPageReqIdl_DataReq::kWithFloorFieldNumber;
const int PbPageReqIdl_DataReq::kFloorRnFieldNumber;
const int PbPageReqIdl_DataReq::kRnFieldNumber;
const int PbPageReqIdl_DataReq::kQTypeFieldNumber;
const int PbPageReqIdl_DataReq::kPnFieldNumber;
const int PbPageReqIdl_DataReq::kIsCommReverseFieldNumber;
const int PbPageReqIdl_DataReq::kIsJumpfloorFieldNumber;
const int PbPageReqIdl_DataReq::kJumpfloorNumFieldNumber;
const int PbPageReqIdl_DataReq::kFloorSortTypeFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

PbPageReqIdl_DataReq::PbPageReqIdl_DataReq()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_PbPageReqIdl_2eproto::InitDefaultsPbPageReqIdl_DataReq();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:PbPageReqIdl.DataReq)
}
PbPageReqIdl_DataReq::PbPageReqIdl_DataReq(const PbPageReqIdl_DataReq& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.has_common()) {
    common_ = new ::CommonReq(*from.common_);
  } else {
    common_ = NULL;
  }
  ::memcpy(&kz_, &from.kz_,
    static_cast<size_t>(reinterpret_cast<char*>(&floor_sort_type_) -
    reinterpret_cast<char*>(&kz_)) + sizeof(floor_sort_type_));
  // @@protoc_insertion_point(copy_constructor:PbPageReqIdl.DataReq)
}

void PbPageReqIdl_DataReq::SharedCtor() {
  ::memset(&common_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&floor_sort_type_) -
      reinterpret_cast<char*>(&common_)) + sizeof(floor_sort_type_));
  _cached_size_ = 0;
}

PbPageReqIdl_DataReq::~PbPageReqIdl_DataReq() {
  // @@protoc_insertion_point(destructor:PbPageReqIdl.DataReq)
  SharedDtor();
}

void PbPageReqIdl_DataReq::SharedDtor() {
  if (this != internal_default_instance()) delete common_;
}

void PbPageReqIdl_DataReq::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* PbPageReqIdl_DataReq::descriptor() {
  ::protobuf_PbPageReqIdl_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_PbPageReqIdl_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const PbPageReqIdl_DataReq& PbPageReqIdl_DataReq::default_instance() {
  ::protobuf_PbPageReqIdl_2eproto::InitDefaultsPbPageReqIdl_DataReq();
  return *internal_default_instance();
}

PbPageReqIdl_DataReq* PbPageReqIdl_DataReq::New(::google::protobuf::Arena* arena) const {
  PbPageReqIdl_DataReq* n = new PbPageReqIdl_DataReq;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void PbPageReqIdl_DataReq::Clear() {
// @@protoc_insertion_point(message_clear_start:PbPageReqIdl.DataReq)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaNoVirtual() == NULL && common_ != NULL) {
    delete common_;
  }
  common_ = NULL;
  ::memset(&kz_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&floor_sort_type_) -
      reinterpret_cast<char*>(&kz_)) + sizeof(floor_sort_type_));
  _internal_metadata_.Clear();
}

bool PbPageReqIdl_DataReq::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:PbPageReqIdl.DataReq)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(16383u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int64 kz = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(32u /* 32 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &kz_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 r = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(48u /* 48 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &r_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 with_floor = 8;
      case 8: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(64u /* 64 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &with_floor_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 floor_rn = 9;
      case 9: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(72u /* 72 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &floor_rn_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 rn = 13;
      case 13: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(104u /* 104 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &rn_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 q_type = 17;
      case 17: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(136u /* 136 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &q_type_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 pn = 18;
      case 18: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(144u /* 144 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &pn_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .CommonReq common = 25;
      case 25: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(202u /* 202 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_common()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 is_comm_reverse = 33;
      case 33: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 264 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &is_comm_reverse_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 is_jumpfloor = 34;
      case 34: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 272 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &is_jumpfloor_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 jumpfloor_num = 35;
      case 35: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 280 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &jumpfloor_num_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 floor_sort_type = 74;
      case 74: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(80u /* 592 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &floor_sort_type_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:PbPageReqIdl.DataReq)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:PbPageReqIdl.DataReq)
  return false;
#undef DO_
}

void PbPageReqIdl_DataReq::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:PbPageReqIdl.DataReq)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 kz = 4;
  if (this->kz() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(4, this->kz(), output);
  }

  // int32 r = 6;
  if (this->r() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(6, this->r(), output);
  }

  // int32 with_floor = 8;
  if (this->with_floor() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(8, this->with_floor(), output);
  }

  // int32 floor_rn = 9;
  if (this->floor_rn() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(9, this->floor_rn(), output);
  }

  // int32 rn = 13;
  if (this->rn() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(13, this->rn(), output);
  }

  // int32 q_type = 17;
  if (this->q_type() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(17, this->q_type(), output);
  }

  // int32 pn = 18;
  if (this->pn() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(18, this->pn(), output);
  }

  // .CommonReq common = 25;
  if (this->has_common()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      25, *this->common_, output);
  }

  // int32 is_comm_reverse = 33;
  if (this->is_comm_reverse() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(33, this->is_comm_reverse(), output);
  }

  // int32 is_jumpfloor = 34;
  if (this->is_jumpfloor() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(34, this->is_jumpfloor(), output);
  }

  // int32 jumpfloor_num = 35;
  if (this->jumpfloor_num() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(35, this->jumpfloor_num(), output);
  }

  // int32 floor_sort_type = 74;
  if (this->floor_sort_type() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(74, this->floor_sort_type(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:PbPageReqIdl.DataReq)
}

::google::protobuf::uint8* PbPageReqIdl_DataReq::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:PbPageReqIdl.DataReq)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 kz = 4;
  if (this->kz() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(4, this->kz(), target);
  }

  // int32 r = 6;
  if (this->r() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(6, this->r(), target);
  }

  // int32 with_floor = 8;
  if (this->with_floor() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(8, this->with_floor(), target);
  }

  // int32 floor_rn = 9;
  if (this->floor_rn() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(9, this->floor_rn(), target);
  }

  // int32 rn = 13;
  if (this->rn() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(13, this->rn(), target);
  }

  // int32 q_type = 17;
  if (this->q_type() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(17, this->q_type(), target);
  }

  // int32 pn = 18;
  if (this->pn() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(18, this->pn(), target);
  }

  // .CommonReq common = 25;
  if (this->has_common()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        25, *this->common_, deterministic, target);
  }

  // int32 is_comm_reverse = 33;
  if (this->is_comm_reverse() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(33, this->is_comm_reverse(), target);
  }

  // int32 is_jumpfloor = 34;
  if (this->is_jumpfloor() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(34, this->is_jumpfloor(), target);
  }

  // int32 jumpfloor_num = 35;
  if (this->jumpfloor_num() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(35, this->jumpfloor_num(), target);
  }

  // int32 floor_sort_type = 74;
  if (this->floor_sort_type() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(74, this->floor_sort_type(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:PbPageReqIdl.DataReq)
  return target;
}

size_t PbPageReqIdl_DataReq::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:PbPageReqIdl.DataReq)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // .CommonReq common = 25;
  if (this->has_common()) {
    total_size += 2 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *this->common_);
  }

  // int64 kz = 4;
  if (this->kz() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->kz());
  }

  // int32 r = 6;
  if (this->r() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->r());
  }

  // int32 with_floor = 8;
  if (this->with_floor() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->with_floor());
  }

  // int32 floor_rn = 9;
  if (this->floor_rn() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->floor_rn());
  }

  // int32 rn = 13;
  if (this->rn() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->rn());
  }

  // int32 q_type = 17;
  if (this->q_type() != 0) {
    total_size += 2 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->q_type());
  }

  // int32 pn = 18;
  if (this->pn() != 0) {
    total_size += 2 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->pn());
  }

  // int32 is_comm_reverse = 33;
  if (this->is_comm_reverse() != 0) {
    total_size += 2 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->is_comm_reverse());
  }

  // int32 is_jumpfloor = 34;
  if (this->is_jumpfloor() != 0) {
    total_size += 2 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->is_jumpfloor());
  }

  // int32 jumpfloor_num = 35;
  if (this->jumpfloor_num() != 0) {
    total_size += 2 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->jumpfloor_num());
  }

  // int32 floor_sort_type = 74;
  if (this->floor_sort_type() != 0) {
    total_size += 2 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->floor_sort_type());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void PbPageReqIdl_DataReq::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:PbPageReqIdl.DataReq)
  GOOGLE_DCHECK_NE(&from, this);
  const PbPageReqIdl_DataReq* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const PbPageReqIdl_DataReq>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:PbPageReqIdl.DataReq)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:PbPageReqIdl.DataReq)
    MergeFrom(*source);
  }
}

void PbPageReqIdl_DataReq::MergeFrom(const PbPageReqIdl_DataReq& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:PbPageReqIdl.DataReq)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_common()) {
    mutable_common()->::CommonReq::MergeFrom(from.common());
  }
  if (from.kz() != 0) {
    set_kz(from.kz());
  }
  if (from.r() != 0) {
    set_r(from.r());
  }
  if (from.with_floor() != 0) {
    set_with_floor(from.with_floor());
  }
  if (from.floor_rn() != 0) {
    set_floor_rn(from.floor_rn());
  }
  if (from.rn() != 0) {
    set_rn(from.rn());
  }
  if (from.q_type() != 0) {
    set_q_type(from.q_type());
  }
  if (from.pn() != 0) {
    set_pn(from.pn());
  }
  if (from.is_comm_reverse() != 0) {
    set_is_comm_reverse(from.is_comm_reverse());
  }
  if (from.is_jumpfloor() != 0) {
    set_is_jumpfloor(from.is_jumpfloor());
  }
  if (from.jumpfloor_num() != 0) {
    set_jumpfloor_num(from.jumpfloor_num());
  }
  if (from.floor_sort_type() != 0) {
    set_floor_sort_type(from.floor_sort_type());
  }
}

void PbPageReqIdl_DataReq::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:PbPageReqIdl.DataReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PbPageReqIdl_DataReq::CopyFrom(const PbPageReqIdl_DataReq& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:PbPageReqIdl.DataReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PbPageReqIdl_DataReq::IsInitialized() const {
  return true;
}

void PbPageReqIdl_DataReq::Swap(PbPageReqIdl_DataReq* other) {
  if (other == this) return;
  InternalSwap(other);
}
void PbPageReqIdl_DataReq::InternalSwap(PbPageReqIdl_DataReq* other) {
  using std::swap;
  swap(common_, other->common_);
  swap(kz_, other->kz_);
  swap(r_, other->r_);
  swap(with_floor_, other->with_floor_);
  swap(floor_rn_, other->floor_rn_);
  swap(rn_, other->rn_);
  swap(q_type_, other->q_type_);
  swap(pn_, other->pn_);
  swap(is_comm_reverse_, other->is_comm_reverse_);
  swap(is_jumpfloor_, other->is_jumpfloor_);
  swap(jumpfloor_num_, other->jumpfloor_num_);
  swap(floor_sort_type_, other->floor_sort_type_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata PbPageReqIdl_DataReq::GetMetadata() const {
  protobuf_PbPageReqIdl_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_PbPageReqIdl_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void PbPageReqIdl::InitAsDefaultInstance() {
  ::_PbPageReqIdl_default_instance_._instance.get_mutable()->data_ = const_cast< ::PbPageReqIdl_DataReq*>(
      ::PbPageReqIdl_DataReq::internal_default_instance());
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int PbPageReqIdl::kDataFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

PbPageReqIdl::PbPageReqIdl()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_PbPageReqIdl_2eproto::InitDefaultsPbPageReqIdl();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:PbPageReqIdl)
}
PbPageReqIdl::PbPageReqIdl(const PbPageReqIdl& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.has_data()) {
    data_ = new ::PbPageReqIdl_DataReq(*from.data_);
  } else {
    data_ = NULL;
  }
  // @@protoc_insertion_point(copy_constructor:PbPageReqIdl)
}

void PbPageReqIdl::SharedCtor() {
  data_ = NULL;
  _cached_size_ = 0;
}

PbPageReqIdl::~PbPageReqIdl() {
  // @@protoc_insertion_point(destructor:PbPageReqIdl)
  SharedDtor();
}

void PbPageReqIdl::SharedDtor() {
  if (this != internal_default_instance()) delete data_;
}

void PbPageReqIdl::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* PbPageReqIdl::descriptor() {
  ::protobuf_PbPageReqIdl_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_PbPageReqIdl_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const PbPageReqIdl& PbPageReqIdl::default_instance() {
  ::protobuf_PbPageReqIdl_2eproto::InitDefaultsPbPageReqIdl();
  return *internal_default_instance();
}

PbPageReqIdl* PbPageReqIdl::New(::google::protobuf::Arena* arena) const {
  PbPageReqIdl* n = new PbPageReqIdl;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void PbPageReqIdl::Clear() {
// @@protoc_insertion_point(message_clear_start:PbPageReqIdl)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaNoVirtual() == NULL && data_ != NULL) {
    delete data_;
  }
  data_ = NULL;
  _internal_metadata_.Clear();
}

bool PbPageReqIdl::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:PbPageReqIdl)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .PbPageReqIdl.DataReq data = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_data()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:PbPageReqIdl)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:PbPageReqIdl)
  return false;
#undef DO_
}

void PbPageReqIdl::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:PbPageReqIdl)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .PbPageReqIdl.DataReq data = 1;
  if (this->has_data()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, *this->data_, output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:PbPageReqIdl)
}

::google::protobuf::uint8* PbPageReqIdl::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:PbPageReqIdl)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .PbPageReqIdl.DataReq data = 1;
  if (this->has_data()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, *this->data_, deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:PbPageReqIdl)
  return target;
}

size_t PbPageReqIdl::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:PbPageReqIdl)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // .PbPageReqIdl.DataReq data = 1;
  if (this->has_data()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *this->data_);
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void PbPageReqIdl::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:PbPageReqIdl)
  GOOGLE_DCHECK_NE(&from, this);
  const PbPageReqIdl* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const PbPageReqIdl>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:PbPageReqIdl)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:PbPageReqIdl)
    MergeFrom(*source);
  }
}

void PbPageReqIdl::MergeFrom(const PbPageReqIdl& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:PbPageReqIdl)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_data()) {
    mutable_data()->::PbPageReqIdl_DataReq::MergeFrom(from.data());
  }
}

void PbPageReqIdl::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:PbPageReqIdl)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PbPageReqIdl::CopyFrom(const PbPageReqIdl& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:PbPageReqIdl)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PbPageReqIdl::IsInitialized() const {
  return true;
}

void PbPageReqIdl::Swap(PbPageReqIdl* other) {
  if (other == this) return;
  InternalSwap(other);
}
void PbPageReqIdl::InternalSwap(PbPageReqIdl* other) {
  using std::swap;
  swap(data_, other->data_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata PbPageReqIdl::GetMetadata() const {
  protobuf_PbPageReqIdl_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_PbPageReqIdl_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
