// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProfileResIdl.proto

#include "ProfileResIdl.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
        template <typename>
PROTOBUF_CONSTEXPR ProfileResIdl_DataRes_Anti::ProfileResIdl_DataRes_Anti(::_pbi::ConstantInitialized)
    : _impl_{
      /*decltype(_impl_.block_stat_)*/ 0,
      /*decltype(_impl_.hide_stat_)*/ 0,
      /*decltype(_impl_.days_tofree_)*/ 0,
      /*decltype(_impl_._cached_size_)*/ {},
    } {}
struct ProfileResIdl_DataRes_AntiDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ProfileResIdl_DataRes_AntiDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ProfileResIdl_DataRes_AntiDefaultTypeInternal() {}
  union {
    ProfileResIdl_DataRes_Anti _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ProfileResIdl_DataRes_AntiDefaultTypeInternal _ProfileResIdl_DataRes_Anti_default_instance_;
        template <typename>
PROTOBUF_CONSTEXPR ProfileResIdl_DataRes::ProfileResIdl_DataRes(::_pbi::ConstantInitialized)
    : _impl_{
      /*decltype(_impl_._has_bits_)*/ {},
      /*decltype(_impl_._cached_size_)*/ {},
      /*decltype(_impl_.post_list_)*/ {},
      /*decltype(_impl_.user_)*/ nullptr,
      /*decltype(_impl_.anti_stat_)*/ nullptr,
    } {}
struct ProfileResIdl_DataResDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ProfileResIdl_DataResDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ProfileResIdl_DataResDefaultTypeInternal() {}
  union {
    ProfileResIdl_DataRes _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ProfileResIdl_DataResDefaultTypeInternal _ProfileResIdl_DataRes_default_instance_;
        template <typename>
PROTOBUF_CONSTEXPR ProfileResIdl::ProfileResIdl(::_pbi::ConstantInitialized)
    : _impl_{
      /*decltype(_impl_._has_bits_)*/ {},
      /*decltype(_impl_._cached_size_)*/ {},
      /*decltype(_impl_.error_)*/ nullptr,
      /*decltype(_impl_.data_)*/ nullptr,
    } {}
struct ProfileResIdlDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ProfileResIdlDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ProfileResIdlDefaultTypeInternal() {}
  union {
    ProfileResIdl _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ProfileResIdlDefaultTypeInternal _ProfileResIdl_default_instance_;
static ::_pb::Metadata file_level_metadata_ProfileResIdl_2eproto[3];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_ProfileResIdl_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_ProfileResIdl_2eproto = nullptr;
const ::uint32_t TableStruct_ProfileResIdl_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::ProfileResIdl_DataRes_Anti, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::ProfileResIdl_DataRes_Anti, _impl_.block_stat_),
    PROTOBUF_FIELD_OFFSET(::ProfileResIdl_DataRes_Anti, _impl_.hide_stat_),
    PROTOBUF_FIELD_OFFSET(::ProfileResIdl_DataRes_Anti, _impl_.days_tofree_),
    PROTOBUF_FIELD_OFFSET(::ProfileResIdl_DataRes, _impl_._has_bits_),
    PROTOBUF_FIELD_OFFSET(::ProfileResIdl_DataRes, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::ProfileResIdl_DataRes, _impl_.user_),
    PROTOBUF_FIELD_OFFSET(::ProfileResIdl_DataRes, _impl_.anti_stat_),
    PROTOBUF_FIELD_OFFSET(::ProfileResIdl_DataRes, _impl_.post_list_),
    0,
    1,
    ~0u,
    PROTOBUF_FIELD_OFFSET(::ProfileResIdl, _impl_._has_bits_),
    PROTOBUF_FIELD_OFFSET(::ProfileResIdl, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::ProfileResIdl, _impl_.error_),
    PROTOBUF_FIELD_OFFSET(::ProfileResIdl, _impl_.data_),
    0,
    1,
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::ProfileResIdl_DataRes_Anti)},
        {11, 22, -1, sizeof(::ProfileResIdl_DataRes)},
        {25, 35, -1, sizeof(::ProfileResIdl)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::_ProfileResIdl_DataRes_Anti_default_instance_._instance,
    &::_ProfileResIdl_DataRes_default_instance_._instance,
    &::_ProfileResIdl_default_instance_._instance,
};
const char descriptor_table_protodef_ProfileResIdl_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\023ProfileResIdl.proto\032\013Error.proto\032\nUser"
    ".proto\032\022PostInfoList.proto\"\203\002\n\rProfileRe"
    "sIdl\022\025\n\005error\030\001 \001(\0132\006.Error\022$\n\004data\030\002 \001("
    "\0132\026.ProfileResIdl.DataRes\032\264\001\n\007DataRes\022\023\n"
    "\004user\030\001 \001(\0132\005.User\022.\n\tanti_stat\030\002 \001(\0132\033."
    "ProfileResIdl.DataRes.Anti\022 \n\tpost_list\030"
    "\004 \003(\0132\r.PostInfoList\032B\n\004Anti\022\022\n\nblock_st"
    "at\030\006 \001(\005\022\021\n\thide_stat\030\007 \001(\005\022\023\n\013days_tofr"
    "ee\030\t \001(\005b\006proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_ProfileResIdl_2eproto_deps[3] =
    {
        &::descriptor_table_Error_2eproto,
        &::descriptor_table_PostInfoList_2eproto,
        &::descriptor_table_User_2eproto,
};
static ::absl::once_flag descriptor_table_ProfileResIdl_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_ProfileResIdl_2eproto = {
    false,
    false,
    336,
    descriptor_table_protodef_ProfileResIdl_2eproto,
    "ProfileResIdl.proto",
    &descriptor_table_ProfileResIdl_2eproto_once,
    descriptor_table_ProfileResIdl_2eproto_deps,
    3,
    3,
    schemas,
    file_default_instances,
    TableStruct_ProfileResIdl_2eproto::offsets,
    file_level_metadata_ProfileResIdl_2eproto,
    file_level_enum_descriptors_ProfileResIdl_2eproto,
    file_level_service_descriptors_ProfileResIdl_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_ProfileResIdl_2eproto_getter() {
  return &descriptor_table_ProfileResIdl_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_ProfileResIdl_2eproto(&descriptor_table_ProfileResIdl_2eproto);
// ===================================================================

class ProfileResIdl_DataRes_Anti::_Internal {
 public:
};

ProfileResIdl_DataRes_Anti::ProfileResIdl_DataRes_Anti(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:ProfileResIdl.DataRes.Anti)
}
ProfileResIdl_DataRes_Anti::ProfileResIdl_DataRes_Anti(const ProfileResIdl_DataRes_Anti& from)
    : ::google::protobuf::Message(), _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:ProfileResIdl.DataRes.Anti)
}
inline void ProfileResIdl_DataRes_Anti::SharedCtor(::_pb::Arena* arena) {
  (void)arena;
  new (&_impl_) Impl_{
      decltype(_impl_.block_stat_){0},
      decltype(_impl_.hide_stat_){0},
      decltype(_impl_.days_tofree_){0},
      /*decltype(_impl_._cached_size_)*/ {},
  };
}
ProfileResIdl_DataRes_Anti::~ProfileResIdl_DataRes_Anti() {
  // @@protoc_insertion_point(destructor:ProfileResIdl.DataRes.Anti)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void ProfileResIdl_DataRes_Anti::SharedDtor() {
  ABSL_DCHECK(GetArenaForAllocation() == nullptr);
}
void ProfileResIdl_DataRes_Anti::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

PROTOBUF_NOINLINE void ProfileResIdl_DataRes_Anti::Clear() {
// @@protoc_insertion_point(message_clear_start:ProfileResIdl.DataRes.Anti)
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.block_stat_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.days_tofree_) -
      reinterpret_cast<char*>(&_impl_.block_stat_)) + sizeof(_impl_.days_tofree_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* ProfileResIdl_DataRes_Anti::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 0, 2> ProfileResIdl_DataRes_Anti::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    9, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294966943,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_ProfileResIdl_DataRes_Anti_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // int32 days_tofree = 9;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ProfileResIdl_DataRes_Anti, _impl_.days_tofree_), 63>(),
     {72, 63, 0, PROTOBUF_FIELD_OFFSET(ProfileResIdl_DataRes_Anti, _impl_.days_tofree_)}},
    // int32 block_stat = 6;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ProfileResIdl_DataRes_Anti, _impl_.block_stat_), 63>(),
     {48, 63, 0, PROTOBUF_FIELD_OFFSET(ProfileResIdl_DataRes_Anti, _impl_.block_stat_)}},
    // int32 hide_stat = 7;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ProfileResIdl_DataRes_Anti, _impl_.hide_stat_), 63>(),
     {56, 63, 0, PROTOBUF_FIELD_OFFSET(ProfileResIdl_DataRes_Anti, _impl_.hide_stat_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 block_stat = 6;
    {PROTOBUF_FIELD_OFFSET(ProfileResIdl_DataRes_Anti, _impl_.block_stat_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // int32 hide_stat = 7;
    {PROTOBUF_FIELD_OFFSET(ProfileResIdl_DataRes_Anti, _impl_.hide_stat_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // int32 days_tofree = 9;
    {PROTOBUF_FIELD_OFFSET(ProfileResIdl_DataRes_Anti, _impl_.days_tofree_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* ProfileResIdl_DataRes_Anti::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ProfileResIdl.DataRes.Anti)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int32 block_stat = 6;
  if (this->_internal_block_stat() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<6>(
            stream, this->_internal_block_stat(), target);
  }

  // int32 hide_stat = 7;
  if (this->_internal_hide_stat() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<7>(
            stream, this->_internal_hide_stat(), target);
  }

  // int32 days_tofree = 9;
  if (this->_internal_days_tofree() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<9>(
            stream, this->_internal_days_tofree(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ProfileResIdl.DataRes.Anti)
  return target;
}

::size_t ProfileResIdl_DataRes_Anti::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ProfileResIdl.DataRes.Anti)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int32 block_stat = 6;
  if (this->_internal_block_stat() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_block_stat());
  }

  // int32 hide_stat = 7;
  if (this->_internal_hide_stat() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_hide_stat());
  }

  // int32 days_tofree = 9;
  if (this->_internal_days_tofree() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_days_tofree());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData ProfileResIdl_DataRes_Anti::_class_data_ = {
    ::google::protobuf::Message::CopyWithSourceCheck,
    ProfileResIdl_DataRes_Anti::MergeImpl
};
const ::google::protobuf::Message::ClassData*ProfileResIdl_DataRes_Anti::GetClassData() const { return &_class_data_; }


void ProfileResIdl_DataRes_Anti::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<ProfileResIdl_DataRes_Anti*>(&to_msg);
  auto& from = static_cast<const ProfileResIdl_DataRes_Anti&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ProfileResIdl.DataRes.Anti)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_block_stat() != 0) {
    _this->_internal_set_block_stat(from._internal_block_stat());
  }
  if (from._internal_hide_stat() != 0) {
    _this->_internal_set_hide_stat(from._internal_hide_stat());
  }
  if (from._internal_days_tofree() != 0) {
    _this->_internal_set_days_tofree(from._internal_days_tofree());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ProfileResIdl_DataRes_Anti::CopyFrom(const ProfileResIdl_DataRes_Anti& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ProfileResIdl.DataRes.Anti)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool ProfileResIdl_DataRes_Anti::IsInitialized() const {
  return true;
}

void ProfileResIdl_DataRes_Anti::InternalSwap(ProfileResIdl_DataRes_Anti* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ProfileResIdl_DataRes_Anti, _impl_.days_tofree_)
      + sizeof(ProfileResIdl_DataRes_Anti::_impl_.days_tofree_)
      - PROTOBUF_FIELD_OFFSET(ProfileResIdl_DataRes_Anti, _impl_.block_stat_)>(
          reinterpret_cast<char*>(&_impl_.block_stat_),
          reinterpret_cast<char*>(&other->_impl_.block_stat_));
}

::google::protobuf::Metadata ProfileResIdl_DataRes_Anti::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_ProfileResIdl_2eproto_getter, &descriptor_table_ProfileResIdl_2eproto_once,
      file_level_metadata_ProfileResIdl_2eproto[0]);
}
// ===================================================================

class ProfileResIdl_DataRes::_Internal {
 public:
  using HasBits = decltype(std::declval<ProfileResIdl_DataRes>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(ProfileResIdl_DataRes, _impl_._has_bits_);
  static const ::User& user(const ProfileResIdl_DataRes* msg);
  static void set_has_user(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static const ::ProfileResIdl_DataRes_Anti& anti_stat(const ProfileResIdl_DataRes* msg);
  static void set_has_anti_stat(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
};

const ::User& ProfileResIdl_DataRes::_Internal::user(const ProfileResIdl_DataRes* msg) {
  return *msg->_impl_.user_;
}
const ::ProfileResIdl_DataRes_Anti& ProfileResIdl_DataRes::_Internal::anti_stat(const ProfileResIdl_DataRes* msg) {
  return *msg->_impl_.anti_stat_;
}
void ProfileResIdl_DataRes::clear_user() {
  if (_impl_.user_ != nullptr) _impl_.user_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
void ProfileResIdl_DataRes::clear_post_list() {
  _internal_mutable_post_list()->Clear();
}
ProfileResIdl_DataRes::ProfileResIdl_DataRes(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:ProfileResIdl.DataRes)
}
ProfileResIdl_DataRes::ProfileResIdl_DataRes(const ProfileResIdl_DataRes& from) : ::google::protobuf::Message() {
  ProfileResIdl_DataRes* const _this = this;
  (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_},
      /*decltype(_impl_._cached_size_)*/ {},
      decltype(_impl_.post_list_){from._impl_.post_list_},
      decltype(_impl_.user_){nullptr},
      decltype(_impl_.anti_stat_){nullptr},
  };
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  if ((from._impl_._has_bits_[0] & 0x00000001u) != 0) {
    _this->_impl_.user_ = new ::User(*from._impl_.user_);
  }
  if ((from._impl_._has_bits_[0] & 0x00000002u) != 0) {
    _this->_impl_.anti_stat_ = new ::ProfileResIdl_DataRes_Anti(*from._impl_.anti_stat_);
  }

  // @@protoc_insertion_point(copy_constructor:ProfileResIdl.DataRes)
}
inline void ProfileResIdl_DataRes::SharedCtor(::_pb::Arena* arena) {
  (void)arena;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){},
      /*decltype(_impl_._cached_size_)*/ {},
      decltype(_impl_.post_list_){arena},
      decltype(_impl_.user_){nullptr},
      decltype(_impl_.anti_stat_){nullptr},
  };
}
ProfileResIdl_DataRes::~ProfileResIdl_DataRes() {
  // @@protoc_insertion_point(destructor:ProfileResIdl.DataRes)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void ProfileResIdl_DataRes::SharedDtor() {
  ABSL_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.post_list_.~RepeatedPtrField();
  if (this != internal_default_instance()) delete _impl_.user_;
  if (this != internal_default_instance()) delete _impl_.anti_stat_;
}
void ProfileResIdl_DataRes::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

PROTOBUF_NOINLINE void ProfileResIdl_DataRes::Clear() {
// @@protoc_insertion_point(message_clear_start:ProfileResIdl.DataRes)
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _internal_mutable_post_list()->Clear();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      ABSL_DCHECK(_impl_.user_ != nullptr);
      _impl_.user_->Clear();
    }
    if (cached_has_bits & 0x00000002u) {
      ABSL_DCHECK(_impl_.anti_stat_ != nullptr);
      _impl_.anti_stat_->Clear();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* ProfileResIdl_DataRes::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 3, 0, 2> ProfileResIdl_DataRes::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(ProfileResIdl_DataRes, _impl_._has_bits_),
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967284,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    3,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_ProfileResIdl_DataRes_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // repeated .PostInfoList post_list = 4;
    {::_pbi::TcParser::FastMtR1,
     {34, 63, 2, PROTOBUF_FIELD_OFFSET(ProfileResIdl_DataRes, _impl_.post_list_)}},
    // .User user = 1;
    {::_pbi::TcParser::FastMtS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(ProfileResIdl_DataRes, _impl_.user_)}},
    // .ProfileResIdl.DataRes.Anti anti_stat = 2;
    {::_pbi::TcParser::FastMtS1,
     {18, 1, 1, PROTOBUF_FIELD_OFFSET(ProfileResIdl_DataRes, _impl_.anti_stat_)}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // .User user = 1;
    {PROTOBUF_FIELD_OFFSET(ProfileResIdl_DataRes, _impl_.user_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .ProfileResIdl.DataRes.Anti anti_stat = 2;
    {PROTOBUF_FIELD_OFFSET(ProfileResIdl_DataRes, _impl_.anti_stat_), _Internal::kHasBitsOffset + 1, 1,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // repeated .PostInfoList post_list = 4;
    {PROTOBUF_FIELD_OFFSET(ProfileResIdl_DataRes, _impl_.post_list_), -1, 2,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::User>()},
    {::_pbi::TcParser::GetTable<::ProfileResIdl_DataRes_Anti>()},
    {::_pbi::TcParser::GetTable<::PostInfoList>()},
  }}, {{
  }},
};

::uint8_t* ProfileResIdl_DataRes::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ProfileResIdl.DataRes)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // .User user = 1;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::user(this),
        _Internal::user(this).GetCachedSize(), target, stream);
  }

  // .ProfileResIdl.DataRes.Anti anti_stat = 2;
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessage(2, _Internal::anti_stat(this),
        _Internal::anti_stat(this).GetCachedSize(), target, stream);
  }

  // repeated .PostInfoList post_list = 4;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_post_list_size()); i < n; i++) {
    const auto& repfield = this->_internal_post_list().Get(i);
    target = ::google::protobuf::internal::WireFormatLite::
        InternalWriteMessage(4, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ProfileResIdl.DataRes)
  return target;
}

::size_t ProfileResIdl_DataRes::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ProfileResIdl.DataRes)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .PostInfoList post_list = 4;
  total_size += 1UL * this->_internal_post_list_size();
  for (const auto& msg : this->_internal_post_list()) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
  }
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    // .User user = 1;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          *_impl_.user_);
    }

    // .ProfileResIdl.DataRes.Anti anti_stat = 2;
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          *_impl_.anti_stat_);
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData ProfileResIdl_DataRes::_class_data_ = {
    ::google::protobuf::Message::CopyWithSourceCheck,
    ProfileResIdl_DataRes::MergeImpl
};
const ::google::protobuf::Message::ClassData*ProfileResIdl_DataRes::GetClassData() const { return &_class_data_; }


void ProfileResIdl_DataRes::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<ProfileResIdl_DataRes*>(&to_msg);
  auto& from = static_cast<const ProfileResIdl_DataRes&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ProfileResIdl.DataRes)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_post_list()->MergeFrom(from._internal_post_list());
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_mutable_user()->::User::MergeFrom(
          from._internal_user());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_internal_mutable_anti_stat()->::ProfileResIdl_DataRes_Anti::MergeFrom(
          from._internal_anti_stat());
    }
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ProfileResIdl_DataRes::CopyFrom(const ProfileResIdl_DataRes& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ProfileResIdl.DataRes)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool ProfileResIdl_DataRes::IsInitialized() const {
  return true;
}

void ProfileResIdl_DataRes::InternalSwap(ProfileResIdl_DataRes* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.post_list_.InternalSwap(&other->_impl_.post_list_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ProfileResIdl_DataRes, _impl_.anti_stat_)
      + sizeof(ProfileResIdl_DataRes::_impl_.anti_stat_)
      - PROTOBUF_FIELD_OFFSET(ProfileResIdl_DataRes, _impl_.user_)>(
          reinterpret_cast<char*>(&_impl_.user_),
          reinterpret_cast<char*>(&other->_impl_.user_));
}

::google::protobuf::Metadata ProfileResIdl_DataRes::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_ProfileResIdl_2eproto_getter, &descriptor_table_ProfileResIdl_2eproto_once,
      file_level_metadata_ProfileResIdl_2eproto[1]);
}
// ===================================================================

class ProfileResIdl::_Internal {
 public:
  using HasBits = decltype(std::declval<ProfileResIdl>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(ProfileResIdl, _impl_._has_bits_);
  static const ::Error& error(const ProfileResIdl* msg);
  static void set_has_error(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static const ::ProfileResIdl_DataRes& data(const ProfileResIdl* msg);
  static void set_has_data(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
};

const ::Error& ProfileResIdl::_Internal::error(const ProfileResIdl* msg) {
  return *msg->_impl_.error_;
}
const ::ProfileResIdl_DataRes& ProfileResIdl::_Internal::data(const ProfileResIdl* msg) {
  return *msg->_impl_.data_;
}
void ProfileResIdl::clear_error() {
  if (_impl_.error_ != nullptr) _impl_.error_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
ProfileResIdl::ProfileResIdl(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:ProfileResIdl)
}
ProfileResIdl::ProfileResIdl(const ProfileResIdl& from) : ::google::protobuf::Message() {
  ProfileResIdl* const _this = this;
  (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_},
      /*decltype(_impl_._cached_size_)*/ {},
      decltype(_impl_.error_){nullptr},
      decltype(_impl_.data_){nullptr},
  };
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  if ((from._impl_._has_bits_[0] & 0x00000001u) != 0) {
    _this->_impl_.error_ = new ::Error(*from._impl_.error_);
  }
  if ((from._impl_._has_bits_[0] & 0x00000002u) != 0) {
    _this->_impl_.data_ = new ::ProfileResIdl_DataRes(*from._impl_.data_);
  }

  // @@protoc_insertion_point(copy_constructor:ProfileResIdl)
}
inline void ProfileResIdl::SharedCtor(::_pb::Arena* arena) {
  (void)arena;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){},
      /*decltype(_impl_._cached_size_)*/ {},
      decltype(_impl_.error_){nullptr},
      decltype(_impl_.data_){nullptr},
  };
}
ProfileResIdl::~ProfileResIdl() {
  // @@protoc_insertion_point(destructor:ProfileResIdl)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void ProfileResIdl::SharedDtor() {
  ABSL_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.error_;
  if (this != internal_default_instance()) delete _impl_.data_;
}
void ProfileResIdl::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

PROTOBUF_NOINLINE void ProfileResIdl::Clear() {
// @@protoc_insertion_point(message_clear_start:ProfileResIdl)
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      ABSL_DCHECK(_impl_.error_ != nullptr);
      _impl_.error_->Clear();
    }
    if (cached_has_bits & 0x00000002u) {
      ABSL_DCHECK(_impl_.data_ != nullptr);
      _impl_.data_->Clear();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* ProfileResIdl::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 2, 0, 2> ProfileResIdl::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(ProfileResIdl, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_ProfileResIdl_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // .ProfileResIdl.DataRes data = 2;
    {::_pbi::TcParser::FastMtS1,
     {18, 1, 1, PROTOBUF_FIELD_OFFSET(ProfileResIdl, _impl_.data_)}},
    // .Error error = 1;
    {::_pbi::TcParser::FastMtS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(ProfileResIdl, _impl_.error_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .Error error = 1;
    {PROTOBUF_FIELD_OFFSET(ProfileResIdl, _impl_.error_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .ProfileResIdl.DataRes data = 2;
    {PROTOBUF_FIELD_OFFSET(ProfileResIdl, _impl_.data_), _Internal::kHasBitsOffset + 1, 1,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::Error>()},
    {::_pbi::TcParser::GetTable<::ProfileResIdl_DataRes>()},
  }}, {{
  }},
};

::uint8_t* ProfileResIdl::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ProfileResIdl)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // .Error error = 1;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::error(this),
        _Internal::error(this).GetCachedSize(), target, stream);
  }

  // .ProfileResIdl.DataRes data = 2;
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessage(2, _Internal::data(this),
        _Internal::data(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ProfileResIdl)
  return target;
}

::size_t ProfileResIdl::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ProfileResIdl)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    // .Error error = 1;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          *_impl_.error_);
    }

    // .ProfileResIdl.DataRes data = 2;
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          *_impl_.data_);
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData ProfileResIdl::_class_data_ = {
    ::google::protobuf::Message::CopyWithSourceCheck,
    ProfileResIdl::MergeImpl
};
const ::google::protobuf::Message::ClassData*ProfileResIdl::GetClassData() const { return &_class_data_; }


void ProfileResIdl::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<ProfileResIdl*>(&to_msg);
  auto& from = static_cast<const ProfileResIdl&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ProfileResIdl)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_mutable_error()->::Error::MergeFrom(
          from._internal_error());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_internal_mutable_data()->::ProfileResIdl_DataRes::MergeFrom(
          from._internal_data());
    }
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ProfileResIdl::CopyFrom(const ProfileResIdl& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ProfileResIdl)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool ProfileResIdl::IsInitialized() const {
  return true;
}

void ProfileResIdl::InternalSwap(ProfileResIdl* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ProfileResIdl, _impl_.data_)
      + sizeof(ProfileResIdl::_impl_.data_)
      - PROTOBUF_FIELD_OFFSET(ProfileResIdl, _impl_.error_)>(
          reinterpret_cast<char*>(&_impl_.error_),
          reinterpret_cast<char*>(&other->_impl_.error_));
}

::google::protobuf::Metadata ProfileResIdl::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_ProfileResIdl_2eproto_getter, &descriptor_table_ProfileResIdl_2eproto_once,
      file_level_metadata_ProfileResIdl_2eproto[2]);
}
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
